### ISSUE TITLE
When is the documentation coming ?

### ISSUE THREAD

**Issue by CodingSoot** [marcglasberg/bdd_framework#1]
Hello,
I've been searching for BDD packages, and yours seems promising. However, there's no documentation yet. When do you plan to add it?

Thanks

**Comment by marcglasberg** [comment]
I'll be working on this this week and the next!

**Comment by marcglasberg** [comment]
Sorry it took much longer than I expected. But finally the documentation is in place.

**Comment by marcglasberg** [comment]
@CodingSoot 
Even more documentation now. And a plugin to support the package.

**Comment by CodingSoot** [comment]
@marcglasberg Thanks, looks great!
